### ISSUE TITLE
`npm run build` with express: TypeError: Q is not a function

### ISSUE THREAD

**Issue by bbigras** [wmalarski/qwik-next-auth-example#1]
Note that I'm assuming I need an adaptor like express to deploy qwik in prod.

I'm `brunoqc` in discord if you need anything.

```sh
gh repo clone wmalarski/qwik-next-auth-example

cd qwik-next-auth-example

npm install

# add express
npm run qwik add

cat >.env <<EOF
VITE_NEXTAUTH_URL=http://localhost
VITE_NEXTAUTH_SECRET=test
EOF

npm run build
```

```
error during build:
TypeError: Q is not a function
    at file:///home/bbigras/tmp/qwik-next-auth-example/server/@qwik-city-plan.mjs:1:4960
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async mainThread (file:///home/bbigras/tmp/qwik-next-auth-example/node_modules/@builder.io/qwik-city/static/node.mjs:328:25)
    at async Module.generate (file:///home/bbigras/tmp/qwik-next-auth-example/node_modules/@builder.io/qwik-city/static/node.mjs:1380:20)
    at async Module.generate (/home/bbigras/tmp/qwik-next-auth-example/node_modules/@builder.io/qwik-city/static/index.cjs:28:18)
    at async Object.closeBundle (/home/bbigras/tmp/qwik-next-auth-example/node_modules/@builder.io/qwik-city/adaptors/express/vite/index.cjs:130:34)
    at async Promise.all (index 1)
    at async PluginDriver.hookParallel (file:///home/bbigras/tmp/qwik-next-auth-example/node_modules/rollup/dist/es/shared/rollup.js:22676:9)
```

**Comment by bbigras** [comment]
Any ideas?

**Comment by wmalarski** [comment]
Hello @bbigras . Just pushed fix to master. It seems like expressAdaptor `staticGenerate` option is colliding with `next-auth.js`. Removed that option.

I think the issue was that `CredentialsProvider` from `next-auth.js` somehow landed in client only assets. And build couldn't resolve that.

**Comment by bbigras** [comment]
`npm run build` seems to work :)

but `npm run serve` has a very similar error message:

```
❯ npm run serve

> serve
> node server/entry.express

file:///home/bbigras/src/qwik-next-auth-example/server/@qwik-city-plan.mjs:1
import{createContext as b,useContext as w,useContextProvider as x,componentQrl as h,inlinedQrl as p,Slot as O,Resource as U,_IMMUTABLE as g}from"@builder.io/qwik";import{jsx as r,jsxs as u}from"@builder.io/qwik/jsx-runtime";import{u as R}from"./assets/index.qwik.3935687c.mjs";import{NextAuthHandler as f}from"next-auth/core";import{z as y}from"zod";import Q from"next-auth/providers/credentials";const D=()=>async e=>{const{getServerSession:t}=await Promise.resolve().then(()=>H),{authOptions:o}=await Promise.resolve().then(()=>V),n=await t(e,o);return{...e,session:n}},B=(e={})=>async t=>{const{getServerSession:o}=await Promise.resolve().then(()=>H),{authOptions:n}=await Promise.resolve().then(()=>V),s=await o(t,n);if(!s)throw t.response.redirect(e.redirectTo||"/api/auth/signin");return{...t,session:s}},q=e=>({query:t=>async o=>t(await e(o)),use:t=>q(async o=>t(await e(o)))}),A=()=>({query:e=>e,use:e=>q(t=>e(t))}),C=b("session-context"),J=e=>{x(C,e)},W=()=>w(C),F=A().use(D()).query(e=>e.session),Y=h(p(()=>{const e=R();return J(e),r("main",{children:r(O,{})})},"s_VkLNXphUh5s")),Z=Object.freeze(Object.defineProperty({__proto__:null,onGet:F,default:Y},Symbol.toStringTag,{value:"Module"})),N=b("session-context"),K=e=>{x(N,e)},ee=()=>w(N),te=A().use(B()).query(e=>e.session.user),oe=h(p(()=>{const e=R();return K(e),r(O,{})},"s_6HnxkjJZMUA")),ne=Object.freeze(Object.defineProperty({__proto__:null,onGet:te,default:oe},Symbol.toStringTag,{value:"Module"})),re=h(p(()=>{const e=W();return u("div",{children:[u("h1",{children:["Welcome to Qwik ",r("span",{class:"lightning",children:"\u26A1\uFE0F"})]}),r("a",{href:"/protected",children:"Protected"}),r(U,{value:e,onPending:()=>r("span",{children:"Pending"}),onRejected:()=>r("span",{children:"Rejected"}),onResolved:t=>u("div",{children:[r("pre",{children:JSON.stringify(t,null,2)}),t?r("a",{href:"/api/auth/signout",children:"Sing Out"}):r("a",{href:"/api/auth/signin",children:"Sign In"})],[g]:{children:!1}}),[g]:{value:!0,onPending:!0,onRejected:!0,onResolved:!0}})]})},"s_xYL1qOwPyDI")),se={title:"Welcome to Qwik"},ie=Object.freeze(Object.defineProperty({__proto__:null,default:re,head:se},Symbol.toStringTag,{value:"Module"})),ce=h(p(()=>{const e=ee();return u("div",{children:[r("h1",{children:"Protected"}),r("a",{href:"/",children:"Home"}),r(U,{value:e,onPending:()=>r("span",{children:"Pending"}),onRejected:()=>r("span",{children:"Rejected"}),onResolved:t=>u("div",{children:[r("h2",{children:"User"}),r("pre",{children:JSON.stringify(t,null,2)})]}),[g]:{value:!0,onPending:!0,onRejected:!0,onResolved:!0}})]})},"s_03435364syU")),ae={title:"Protected route - Welcome to Qwik"},ue=Object.freeze(Object.defineProperty({__proto__:null,default:ce,head:ae},Symbol.toStringTag,{value:"Module"})),de=y.object({VITE_NEXTAUTH_URL:y.string(),VITE_NEXTAUTH_SECRET:y.string()});if(typeof window<"u")throw new Error("server env is on client!!");const d=de.parse({VITE_NEXTAUTH_URL:"http://localhost",VITE_NEXTAUTH_SECRET:"test",BASE_URL:"/",MODE:"production",DEV:!1,PROD:!0}),le=e=>{const t={};return(e||[]).forEach((o,n)=>{n in t?t[n]=Array.isArray(t[n])?[...t[n],o]:[t[n],o]:t[n]=o},{}),t},k="next-auth.temp",I=(e,t)=>{if(!t||t.length<1)return;const o=JSON.stringify(t.map(s=>[s.name,s.value])),n=t[0].options;e.set(k,o,{...n,sameSite:n.sameSite===!0?"strict":n.sameSite===!1?void 0:n.sameSite})},m=e=>{const t=e.get(k),o=t==null?void 0:t.json();return Object.fromEntries(o||[])},E=async(e,t)=>{var j;const{request:o,params:n,url:s,response:i,cookie:l}=e,[X,T]=n.nextauth.split("/");let c;try{const a=await o.formData();c=le(a)}catch{}const S=Object.fromEntries(s.searchParams),v=await f({req:{action:X,body:c,cookies:m(l),error:(j=S.error)!=null?j:T,headers:o.headers,host:d.VITE_NEXTAUTH_URL,method:o.method,providerId:T,query:S},options:t}),{cookies:z,redirect:_,headers:G,status:$}=v;for(const a of G||[])i.headers.append(a.key,a.value);if(I(l,z),_){if((c==null?void 0:c.json)!=="true")throw i.redirect(_,302);return i.headers.set("Content-Type","application/json"),{url:_}}return i.status=$||200,v.body},he=async(e,t)=>{const{request:o,cookie:n}=e,s=await f({req:{action:"session",cookies:m(n),headers:o.headers,host:d.VITE_NEXTAUTH_URL,method:"GET"},options:t}),{body:i,cookies:l}=s;return I(n,l),i&&typeof i!="string"&&Object.keys(i).length?i:null},pe=async(e,t)=>{const{cookie:o,request:n}=e,{body:s}=await f({req:{action:"csrf",cookies:m(o),headers:n.headers,host:d.VITE_NEXTAUTH_URL,method:"GET"},options:t});return s.csrfToken},fe=async(e,t)=>{const{cookie:o,request:n}=e,{body:s}=await f({req:{action:"providers",cookies:m(o),headers:n.headers,host:d.VITE_NEXTAUTH_URL,method:"GET"},options:t});return s&&typeof s!="string"?s:null},L=e=>({onGet:t=>E(t,e),onPost:t=>E(t,e)}),H=Object.freeze(Object.defineProperty({__proto__:null,getServerSession:he,getServerCsrfToken:pe,getServerProviders:fe,NextAuth:L},Symbol.toStringTag,{value:"Module"})),M={secret:d.VITE_NEXTAUTH_SECRET,providers:[Q({name:"Credentials",credentials:{username:{label:"Username",type:"text",placeholder:"jsmith"},password:{label:"Password",type:"password"}},async authorize(e){return(e==null?void 0:e.username)==="admin"&&(e==null?void 0:e.password)==="admin123"?{id:"1",name:e==null?void 0:e.username}:null}})]},V=Object.freeze(Object.defineProperty({__proto__:null,authOptions:M},Symbol.toStringTag,{value:"Module"})),{onGet:me,onPost:_e}=L(M),ye=Object.freeze(Object.defineProperty({__proto__:null,onGet:me,onPost:_e},Symbol.toStringTag,{value:"Module"})),P=()=>Z,ge=()=>ne,Te=[[/^\/$/,[P,()=>ie],void 0,"/",["q-62c21b98.js","q-cb1e72d3.js"]],[/^\/protected\/?$/,[P,ge,()=>ue],void 0,"/protected",["q-62c21b98.js","q-0c7a014e.js","q-c18a31f3.js"]],[/^\/api\/auth(?:\/(.*))?\/?$/,[()=>ye],["nextauth"],"/api/auth/[...nextauth]",["q-62c21b98.js"]]],Se=[],ve=!1,je="/",Ee=!0,Re={routes:Te,menus:Se,trailingSlash:ve,basePathname:je,cacheModules:Ee};export{je as basePathname,Ee as cacheModules,Re as default,Seas menus,Te as routes,ve as trailingSlash};







TypeError: Q is not a function
    at file:///home/bbigras/src/qwik-next-auth-example/server/@qwik-city-plan.mjs:1:4960
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

Node.js v18.12.1
```

**Comment by wmalarski** [comment]
haha, almost there. checking

**Comment by bbigras** [comment]
Any luck?

**Comment by wmalarski** [comment]
No. Everything is fine after removing this import
```ts
import CredentialsProvider from "next-auth/providers/credentials";
```
But the whole point is to have providers...

I can move error from build to startup or runtime but it's always there. Probably some solution could be found after deeper research of build options. Somehow force "next-auth/providers/credentials" to be available on runtime. I did some try and error things but no lack yet.

**Comment by wmalarski** [comment]
I think it should be working now.

It seems like `"next-auth/providers/credentials"` was always available but problem was with imports. Problem was with default export.

I added temporary solution like this:
```ts
import CredentialsProvider from "next-auth/providers/credentials";
import { env } from "../env";

const Credentials =
  typeof CredentialsProvider === "function"
    ? CredentialsProvider
    : ((CredentialsProvider as any).default as typeof CredentialsProvider);
```

**Comment by bbigras** [comment]
It works! Thank you so much! It worked with keycloak too.

```ts
const Keycloak =
  typeof KeycloakProvider === "function"
    ? KeycloakProvider
    : ((KeycloakProvider as any).default as typeof KeycloakProvider);
```
